#!/usr/bin/with-contenv bash

if [ ! -d /media/Music ]; then
  echo "Creating /media/Music"
  mkdir -p /media/Music
  chown -R abc:abc /media/Music
fi

if [ ! -d /share/downloads ]; then
  echo "Creating /share/downloads"
  mkdir -p /share/downloads
  chown -R abc:abc /share/downloads
fi

if [ ! -d /share/lidarr/config ]; then
  echo "Creating /share/lidarr/config"
  mkdir -p /share/lidarr/config
  chown -R abc:abc /share/lidarr/config
fi
